### ISSUE TITLE
什么时候会上传代码呀？

### ISSUE THREAD

**Issue by senlin-ali** [baaivision/Painter#1]
hi、对你们的工作很感兴趣，想问下什么时候会上传代码

**Comment by WXinlong** [comment]
Hi, thanks for your interest. We are preparing for the open source and will release both the code and models. Please stay tuned.:)

**Comment by GewelsJI** [comment]
Hi, @WXinlong 

Thanks for providing a promising work. Do you have any plan to release the project code?

Best.

**Comment by WXinlong** [comment]
@senlin-ali @GewelsJI  The code and model are available now.:)
