### ISSUE TITLE
Is it possible to launch the painter runVideo in local machine

### ISSUE THREAD

**Issue by laozhuang727** [baaivision/Painter#21]
Hi ,

 Painter is a great project. We try to launch it for daily task, and find in the app_gradio.py, it post the request to another server, which make it impossible to do any customize development. 
  r = requests.post("http://120.92.79.209/painter/runVideo", files = files)
Is it possible to launch the painter with the source code in our local server. 

Thanks very much!!

**Comment by WXinlong** [comment]
@laozhuang727  The model and inference code of SegGPT is available now. Please check it out.:)
