### ISSUE TITLE
我想要推理一张图片，怎么编写代码？

### ISSUE THREAD

**Issue by d710055071** [baaivision/Painter#22]
1.我想要达到rainbow.gif的效果， 我应该怎写推理代码？
2.我使用了/Painter/eval/ade20k_semantic/painter_inference_segm.py  输入只有一个类别的mask and 和图片，推理时却识别的都是车一类的东西？

**Comment by d710055071** [comment]
@WXinlong

**Comment by WXinlong** [comment]
@d710055071  The model and inference code of SegGPT is available now. Please check it out.:)
