### ISSUE TITLE
Question about input of evaluation

### ISSUE THREAD

**Issue by mrluin** [baaivision/Painter#3]
Hello,

Thanks for your great work!
What is the format of input in evaluation, directly using the input image or using stitched input?

**Comment by encounter1997** [comment]
Hi, thanks for your interest. During inference, we use the stitched input to align with the training setup.

**Comment by mrluin** [comment]
Thanks, now I am clear about the inference formulation.

Another question about the results of joint training: does the result is obtained by first jointly training on multiple task then finetune on specific target task or directly using the jointly trained model?

**Comment by encounter1997** [comment]
The jointly trained model is directly evaluated on multiple tasks without task-specific fine-tuning.

**Comment by mrluin** [comment]
Thank you very much!
