### ISSUE TITLE
Question about evaluation on denosing task

### ISSUE THREAD

**Issue by Hanqer** [baaivision/Painter#4]
Great work ! I have some question about the evaluation on denosing task.

The input image size is 448x448 by default. However, in the standrad evaluation of SIDD dataset, the PSNR and SSIM are computed on the croped 256x256 image patches. I want to know in this work, the evaluation is conducted on the 256x256 image patches (resize to 448x448 as input) or 448x448 image patches (re-crop the original image to 448 patches) ? 

Thanks!

**Comment by encounter1997** [comment]
Hi, thanks for your interest. 

During inference, we resize the noisy patches from 256x256 to 448x448 to align with the training setup. Afterward, we resize the denoised patches back to 256x256 for evaluation.

**Comment by Hanqer** [comment]
Thanks for your repley! It solves my doubts.
