### ISSUE TITLE
version for mmlab in Painter 

### ISSUE THREAD

**Issue by vvvvvjdy** [baaivision/Painter#62]
what‘s your version about mmcv mmdet and mmpose in Painter project？when I install the latest version about this packages，many modules are not exist.    (such as  cannot import name 'Config' from 'mmcv' )

**Comment by lime-s** [comment]
Have you solved this problem? @vvvvvjdy

**Comment by ananda1995** [comment]
@vvvvvjdy im also getting same issue .
can you please help me to resolve the issue?.

**Comment by vvvvvjdy** [comment]
@ananda1995  Sorry for the late reply. Have you solve the issue? if not , here is the version and it works well on my machine.  
mmcv-full=1.6.0 mmdet=2..26.0 mmpose=0.25.0 mmtrack=0.14.0.

**Comment by wwwloewww** [comment]
> [@ananda1995](https://github.com/ananda1995) Sorry for the late reply. Have you solve the issue? if not , here is the version and it works well on my machine. mmcv-full=1.6.0 mmdet=2..26.0 mmpose=0.25.0 mmtrack=0.14.0.

hello, Can this version handle all the dataset smoothly?

**Comment by wwwloewww** [comment]
> [@ananda1995](https://github.com/ananda1995) Sorry for the late reply. Have you solve the issue? if not , here is the version and it works well on my machine. mmcv-full=1.6.0 mmdet=2..26.0 mmpose=0.25.0 mmtrack=0.14.0.

I in the treatment of the key points in the process of data of the difficulty to find the method of "TopDownGetBboxCenterScale" error, this version can solve the problem, please? @vvvvvjdy
